-- 이건 못 풀겠음.

WITH RECURSIVE GENERATION_DATA AS (
    -- [1] 기준점: 1세대 (부모가 없는 개체)
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- [2] 반복: 자식 찾기 (부모의 세대 + 1)
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    INNER JOIN GENERATION_DATA G ON E.PARENT_ID = G.ID
)
-- [3] 최종 결과: 세대별로 '자식이 없는(누군가의 부모가 아닌)' 개체만 세기
SELECT 
    COUNT(*) AS COUNT, GENERATION
FROM GENERATION_DATA
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;