-- 코드를 작성해주세요
SELECT COUNT(FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO I
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE 
    FROM FISH_NAME_INFO N
    WHERE N.FISH_TYPE = I.FISH_TYPE AND (FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER')
);